### ISSUE TITLE
Implement @InjectResource

### ISSUE THREAD

**Issue by philippkumar** [techatspree/roboject#4]
It would be nice to have a general way to inject an arbitrary resource by id to a field of the activity. One annotation type should be sufficient for that (@|njectResource)
Concrete case we are having is that we want to inject a drawable once and reuse it throughout the activity.

Available resource types:
http://developer.android.com/guide/topics/resources/available-resources.html

**Comment by ebiermann** [comment]
The following resource types should work with and without specifying a value attribute.
String, Integer, Boolean, ColorStateList, Animation, Drawable, Dimen, String-Array and Int-Array.

Other resource types will work only with a provided value id
Color

Additional resource types can be added by adding them to getTypeForField and getResource in AndroidUtil
