### ISSUE TITLE
Honeycomb roboject tests are executed on pre honeycomb devices

### ISSUE THREAD

**Issue by ebiermann** [techatspree/roboject#5]
The integration tests contain tests for Honeycomb and support library fragments. The Honeycomb tests will always fail on non-Honeycomb devices.

Suggestions:
1) Allow honycomb tests to pass successfully on old devices
2) Prevent Honeycomb tests from being executed on older devices or emulators (via maven profile or other means)

**Comment by cescoffier** [comment]
Would be in favor of 1. 
On your CI, you can configure the configuration matrix to be sure they run on Honeycomb.

**Comment by ebiermann** [comment]
Issue fixed. Test will always succeed on pre-Honeycomb
