### ISSUE TITLE
How to with ABS?

### ISSUE THREAD

**Issue by sjbwylbs** [techatspree/roboject#6]
Because java can only extends one Class,so How to use roboject with ABS(actionbarsherlock)?

**Comment by ebiermann** [comment]
Hello,

You are able to do this with the current develop version:
depending on the type of injected object there are several methods available in the Roboject class.
For example if you want to use view injections In one of your activities you could call
Roboject.injectViews(this, this);
You can set up a base activity that extends the ABS activitty similiar to the Roboject Activity:
https://github.com/akquinet/roboject/blob/develop/roboject/src/main/java/de/akquinet/android/roboject/RobojectActivity.java

Note that the current release 1.2.1 on Central does not have this functionality yet and can only use injections by exttending RobojectActivity.

Regards,
Enrico

**Comment by sjbwylbs** [comment]
Good job.Thanks.

**Comment by ebiermann** [comment]
We released Roboject 1.2.2 earlier this week, so it is no longer necessary to use the version from the develop branch.
